### ISSUE TITLE
The Rust Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by djwe** [jonathandturner/rls_vscode#12]
Followed instructions from [here](https://github.com/jonathandturner/rls#vscode-integration). After vscode opens the new window for the plugin I see this in the debug console.
```
The Rust Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.

e.doShow @ messageService.ts:128
e.show @ messageService.ts:107
(anonymous function) @ mainThreadMessageService.ts:55
n.Class.derive._oncancel @ winjs.base.raw.js:164
1t.$showMessage @ mainThreadMessageService.ts:25
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:269
f @ ipcRemoteCom.ts:226
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

I am on latest macOS. How can I debug this issue further? 
Just realized I am using rustup which is not recommended. What is the reason for not using rustup?

**Comment by jonathandturner** [comment]
There are a few things that can cause this.  What I'd suggest doing is looking at the line it's trying to invoke (probably just running 'rls'. If there is stuff with 'jturner' in it, that was a bad commit so update and try again).  Next, see if you can run the same command by hand and get a running rls instance.  

If it just quits immediately or it can't find the rls, you can try putting it in your path.

If the rls fails to run because it can't find missing dynamic lib symbols, this comes from trying to link against the rustc libs that rustup provides.  You can either not use rustup or you can use a hack similar to what I did with https://github.com/jonathandturner/rls_vscode/commit/7d9303e5ddf566c9596940a38e97268d73b2c7cf#diff-45327f86d4438556066de133327f4ca2L17

**Comment by jonathandturner** [comment]
I'm closing this issue.  Recent versions should be better behaved, but please reopen if this issue still shows up.
